"use client"


import type { Metadata } from "next";

import "./globals.css";


import { DndProvider } from "react-dnd"
import { HTML5Backend } from "react-dnd-html5-backend"



// export const metadata: Metadata = {
//   title: "Dynamic Form Builder",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
         <DndProvider backend={HTML5Backend}></DndProvider>
        {children}
      </body>
    </html>
  );
}
